### ISSUE TITLE
Not compatible with ESLint 9

### ISSUE THREAD

**Issue by Arkellys** [marudor/eslint-plugin-sort-imports-es6-autofix#31]
I've recently updated my config to ESLint 9 and flat config, and this plugin sadly doesn't seem compatible.

When an import is not sorted correctly, the plugin makes ESLint crash with an error trown on [this line](https://github.com/marudor/eslint-plugin-sort-imports-es6-autofix/blob/df8411b77dbe22dc01aad84f5f738b1f66f74d8e/rules/sort-imports-es6.js#L279). For example:

```js
import { b, a } from "./test";
```

```shell
Oops! Something went wrong! :(

ESLint: 9.13.0

TypeError: sourceCode.getComments is not a function
Occurred while linting C:\Users\[...]:3
Rule: "sort-imports-es6-autofix/sort-imports-es6"
    at C:\Users\[...]\node_modules\eslint-plugin-sort-imports-es6-autofix\rules\sort-imports-es6.js:279:83
    at Array.some (<anonymous>)
    at Object.fix (C:\Users\[...]\node_modules\eslint-plugin-sort-imports-es6-autofix\rules\sort-imports-es6.js:279:54)
    at normalizeFixes (C:\Users\[...]\node_modules\eslint\lib\linter\report-translator.js:193:28)
    [...]
```

My config is as follow:

```js
import importPlugin from "eslint-plugin-import";
import sortImportsES6Autofix from "eslint-plugin-sort-imports-es6-autofix";

export default [
  importPlugin.flatConfigs.recommended,
  {
    plugins: {
      "sort-imports-es6-autofix": sortImportsES6Autofix
    },
    rules: {
      "sort-imports-es6-autofix/sort-imports-es6": ["warn", {
        ignoreCase: true,
        memberSyntaxSortOrder: ["all", "multiple", "single", "none"]
      }],
      ...
    }
  }
];
```

I know this library has not been updated in a while, but it's actually very useful. Would an update to make it compatible with v9 possible?

**Comment by Arkellys** [comment]
One of ESLint 9 breaking changes is that [it removed the deprecated `sourceCode.getComments()`](https://eslint.org/docs/latest/use/migrate-to-9.0.0#-removed-sourcecodegetcomments).

**Comment by christianottosson** [comment]
I have the same issue, very annoying and was just searching for a solution. I thought I did something wrong when I upgraded to ESLint 9.X

**Comment by Arkellys** [comment]
I don't know anything about coding ESLint plugins, and I can't find where the documentation of `sourceCode` methods is, but I tested quickly and the fix seems to be just as simple as replacing:

```js
importSpecifiers.some(specifier => sourceCode.getComments(specifier).leading.length
|| sourceCode.getComments(specifier).trailing.length
```

With:

```js
importSpecifiers.some(specifier => sourceCode.getCommentsBefore(specifier).length
|| sourceCode.getCommentsAfter(specifier).length
```

All tests passes.

@marudor If someone created a PR to fix this, would you consider accepting it? Or is the lib no longer maintained and we have to patch on our side?

**Comment by marudor** [comment]
@Arkellys It's no longer maintained. Feel free to fork this.
