### ISSUE TITLE
Consider single named imports as single

### ISSUE THREAD

**Issue by sidhu663** [marudor/eslint-plugin-sort-imports-es6-autofix#6]
From the description: The `multiple` type corresponds to all named imports (regardless of how many are imported)

Could this be changed to conform to the eslint rule ? It seems like this can be achieved by adding the following to the `usedMemberSyntax` part of the rule:

```
        function usedMemberSyntax(node) {
            if (node.specifiers.length === 0) {
                return "none";
            } else if (node.specifiers.length > 1) {
                return "multiple"
            } else if (node.specifiers[0].type === "ImportNamespaceSpecifier") {
                return "all";
            } if (node.specifiers.length === 1) {
                return "single"
            }
            return "multiple";
        }
```

Would love to use this but the lack of conformance results in ESLint complaining

**Comment by marudor** [comment]
This is on purpose. I do not agree with it being the same.
